import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../../styles/Home.module.css'
import NavBar from '../components/NavBar';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Kevin Hernon</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/img/kevin2.png" />
      </Head>

      <main>
        <NavBar />
        <h1> Kevin Hernon </h1>
      </main>

      <footer>
      </footer>
    </div>
  )
}

export default Home
