import type { NextPage } from 'next'
import React from 'react';
import Head from 'next/head'
import styles from '../../styles/Home.module.css'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faYoutubeSquare, faFacebook, faLinkedin } from '@fortawesome/free-brands-svg-icons';
import { Button }  from 'react-bootstrap';


const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Kevin Hernon</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/img/kevin2.png" />
      </Head>

      <main className={styles.whiteText}>
        <section className={styles.header}>
          <h1 className={styles.head}> Kevin Hernon </h1>
          <h5 className={styles.subHead}> MBA Student at Seattle University | Video Game Connoisseur | Verteran </h5>
        </section>

        <section className={`${styles.social} ${styles.center}`}>
          <FontAwesomeIcon icon={faLinkedin} size="4x" fixedWidth />
          <FontAwesomeIcon icon={faYoutubeSquare} size="4x" fixedWidth />
          <FontAwesomeIcon icon={faFacebook} size="4x" fixedWidth />
        </section>
        <div className={`${styles.center}`}>
          <Button variant="outline-light" size="lg"> More About Me </Button>
        </div>

      </main>

      <footer>
      </footer>
    </div>
  )
}

export default Home
